#CI项目
name: CUSTOM
run-name: CUSTOM-${{ (inputs.WRT_RELEASE_FIRMWARE || github.event_name == 'schedule') && 'release' || 'test' }}

#CI计划
on:
  schedule:
    - cron: '0 3 1 * *'  # 每月1日 03:00 UTC
  workflow_dispatch:
    inputs:
      WHAT_MY_SAY:
        description: '编译说明'
        required: false
        type: string
        default: ''
      WRT_RELEASE_FIRMWARE:
        description: '是否发布'
        required: false
        type: boolean
        default: true
      WRT_SOURCE_HASH_INFO:
        description: '源码 HASH，可选填写 commit hash'
        required: false
        type: string
        default: ''

#CI权限
permissions: write-all

#CI任务
jobs:
  cmiot_ax18_nowifi_fw3:
    name: CMIOT-AX18-NOWIFI-fw3-base
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      WRT_SOURCE_HASH_INFO: ${{ inputs.WRT_SOURCE_HASH_INFO }}
      WRT_DEVICE: CMIOT-AX18-NOWIFI
      WRT_FIREWALL: fw3
      WRT_OVERLAYS: ''
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DIY_FEEDS: diy_feeds.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: ${{ inputs.WRT_RELEASE_FIRMWARE || github.event_name == 'schedule' }}
      WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
    secrets: inherit

  cmiot_ax18_nowifi_fw3_frps:
    name: CMIOT-AX18-NOWIFI-fw3-frps
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      WRT_SOURCE_HASH_INFO: ${{ inputs.WRT_SOURCE_HASH_INFO }}
      WRT_DEVICE: CMIOT-AX18-NOWIFI
      WRT_FIREWALL: fw3
      WRT_OVERLAYS: frps
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DIY_FEEDS: diy_feeds.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: ${{ inputs.WRT_RELEASE_FIRMWARE || github.event_name == 'schedule' }}
      WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
    secrets: inherit

  gl_mt6000_wifi_fw3:
    name: GL-MT6000-WIFI-fw3-base
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      WRT_SOURCE_HASH_INFO: ${{ inputs.WRT_SOURCE_HASH_INFO }}
      WRT_DEVICE: GL-MT6000-WIFI
      WRT_FIREWALL: fw3
      WRT_OVERLAYS: ''
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DIY_FEEDS: diy_feeds.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: ${{ inputs.WRT_RELEASE_FIRMWARE || github.event_name == 'schedule' }}
      WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
    secrets: inherit

  jd_ax6600_wifi_fw3:
    name: JD-AX6600-WIFI-fw3-base
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      WRT_SOURCE_HASH_INFO: ${{ inputs.WRT_SOURCE_HASH_INFO }}
      WRT_DEVICE: JD-AX6600-WIFI
      WRT_FIREWALL: fw3
      WRT_OVERLAYS: ''
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DIY_FEEDS: diy_feeds.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: ${{ inputs.WRT_RELEASE_FIRMWARE || github.event_name == 'schedule' }}
      WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
    secrets: inherit
