#CI项目
name: CUSTOM-IWRT
run-name: CUSTOM-IWRT-${{ inputs.WRT_RELEASE_FIRMWARE && 'release' || 'test' }}

#CI计划
on:
  # schedule:
  #   - cron: '0 3 1,15 * *'  # 每月1日 03:00 UTC
  workflow_dispatch:
    inputs:
      WHAT_MY_SAY:
        description: '编译说明'
        required: false
        type: string
        default: ''
      WRT_RELEASE_FIRMWARE:
        description: '是否发布'
        required: false
        type: boolean
        default: false
      WRT_SOURCE_HASH_INFO:
        description: '源码 HASH，可选填写 commit hash'
        required: false
        type: string
        default: '9e08f0c3cf44c6681d7f9b7730adf3fad8db62a5' # 'a4638cd4389183f1a1fcad0441f491ca11c97757' #'9e08f0c3cf44c6681d7f9b7730adf3fad8db62a5'

#CI权限
permissions: write-all

#CI任务
jobs:
  # cmiot_ax18_nowifi_fw4:
  #   name: cmiot-ax18-nowifi-fw4-base
  #   uses: ./.github/workflows/CORE-ALL.yml
  #   with:
  #     WRT_SOURCE_HASH_INFO: ${{ inputs.WRT_SOURCE_HASH_INFO }}
  #     WRT_DEVICE: cmiot-ax18-nowifi
  #     SOURCE_TYPE: 'vwrt'
  #     WRT_FIREWALL: auto
  #     WRT_OVERLAYS: ''
  #     WRT_DIY_SETTING: diy_config.sh
  #     WRT_DIYPackages: Packages.sh
  #     WRT_DIY_FEEDS: diy_feeds.sh
  #     WRT_DEFAULT_LANIP: 192.168.0.1
  #     WRT_RELEASE_FIRMWARE: ${{ github.event_name == 'workflow_dispatch' && inputs.WRT_RELEASE_FIRMWARE }}
  #     WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
  #   secrets: inherit

  cmiot_ax18_nowifi_fw4_frps:
    name: cmiot-ax18-nowifi-fw4-frps
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      WRT_SOURCE_HASH_INFO: ${{ inputs.WRT_SOURCE_HASH_INFO }}
      WRT_DEVICE: cmiot-ax18-nowifi
      SOURCE_TYPE: 'vwrt'
      WRT_FIREWALL: auto
      WRT_OVERLAYS: frps
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DIY_FEEDS: diy_feeds.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: ${{ github.event_name == 'workflow_dispatch' && inputs.WRT_RELEASE_FIRMWARE }}
      WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
    secrets: inherit

  gl_mt6000_wifi_fw4:
    name: gl-mt6000-wifi-fw4-base
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      WRT_SOURCE_HASH_INFO: ${{ inputs.WRT_SOURCE_HASH_INFO }}
      WRT_DEVICE: gl-mt6000-wifi
      SOURCE_TYPE: 'vwrt'
      WRT_FIREWALL: auto
      WRT_OVERLAYS: ''
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DIY_FEEDS: diy_feeds.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: ${{ github.event_name == 'workflow_dispatch' && inputs.WRT_RELEASE_FIRMWARE }}
      WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
    secrets: inherit

  jd_ax6600_wifi_fw4:
    name: jd-ax6600-wifi-fw4-base
    uses: ./.github/workflows/CORE-ALL.yml
    with:
      WRT_SOURCE_HASH_INFO: ${{ inputs.WRT_SOURCE_HASH_INFO }}
      WRT_DEVICE: jd-ax6600-wifi
      SOURCE_TYPE: 'vwrt'
      WRT_FIREWALL: auto
      WRT_OVERLAYS: ''
      WRT_DIY_SETTING: diy_config.sh
      WRT_DIYPackages: Packages.sh
      WRT_DIY_FEEDS: diy_feeds.sh
      WRT_DEFAULT_LANIP: 192.168.0.1
      WRT_RELEASE_FIRMWARE: ${{ github.event_name == 'workflow_dispatch' && inputs.WRT_RELEASE_FIRMWARE }}
      WRT_MINE_SAY: ${{ inputs.WHAT_MY_SAY }}
    secrets: inherit
